// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package coin_extender

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Address              string               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol               string               `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               string               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Address) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Address) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "coin_extender.Address")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_982c640dad8fe78e) }

var fileDescriptor_982c640dad8fe78e = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0xce, 0xcf, 0xcc, 0x8b,
	0x4f, 0xad, 0x28, 0x49, 0xcd, 0x4b, 0x49, 0x2d, 0x92, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0x07, 0x4b, 0x26, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16,
	0x40, 0xd4, 0x2b, 0xf5, 0x31, 0x72, 0xb1, 0x3b, 0x42, 0x4c, 0x10, 0x92, 0xe0, 0x62, 0x87, 0x1a,
	0x26, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0x57, 0xe6,
	0x26, 0xe5, 0xe7, 0x48, 0x30, 0x81, 0x25, 0xa0, 0x3c, 0x90, 0x78, 0x62, 0x6e, 0x7e, 0x69, 0x5e,
	0x89, 0x04, 0x33, 0x44, 0x1c, 0xc2, 0x13, 0xb2, 0xe4, 0xe2, 0x4a, 0x2e, 0x4a, 0x4d, 0x2c, 0x49,
	0x4d, 0x89, 0x4f, 0x2c, 0x91, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0xb8, 0x45,
	0x0f, 0xe6, 0x16, 0xbd, 0x10, 0x98, 0x5b, 0x82, 0x38, 0xa1, 0xaa, 0x1d, 0x4b, 0x92, 0xd8, 0xc0,
	0xd2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xbc, 0x6d, 0x3f, 0xd8, 0x00, 0x00, 0x00,
}
