// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coin.proto

package coin_extender

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coin struct {
	Symbol               string               `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price                string               `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Capitalization       string               `protobuf:"bytes,3,opt,name=capitalization,proto3" json:"capitalization,omitempty"`
	ReserveBalance       string               `protobuf:"bytes,4,opt,name=reserve_balance,json=reserveBalance,proto3" json:"reserve_balance,omitempty"`
	Volume               string               `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Coin) Reset()         { *m = Coin{} }
func (m *Coin) String() string { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()    {}
func (*Coin) Descriptor() ([]byte, []int) {
	return fileDescriptor_39141bafd5884f78, []int{0}
}

func (m *Coin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coin.Unmarshal(m, b)
}
func (m *Coin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coin.Marshal(b, m, deterministic)
}
func (m *Coin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coin.Merge(m, src)
}
func (m *Coin) XXX_Size() int {
	return xxx_messageInfo_Coin.Size(m)
}
func (m *Coin) XXX_DiscardUnknown() {
	xxx_messageInfo_Coin.DiscardUnknown(m)
}

var xxx_messageInfo_Coin proto.InternalMessageInfo

func (m *Coin) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Coin) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Coin) GetCapitalization() string {
	if m != nil {
		return m.Capitalization
	}
	return ""
}

func (m *Coin) GetReserveBalance() string {
	if m != nil {
		return m.ReserveBalance
	}
	return ""
}

func (m *Coin) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *Coin) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Coin)(nil), "coin_extender.Coin")
}

func init() { proto.RegisterFile("coin.proto", fileDescriptor_39141bafd5884f78) }

var fileDescriptor_39141bafd5884f78 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x6d, 0x17, 0x3a, 0xa2, 0x42, 0x10, 0x09, 0xbd, 0x58, 0x3c, 0x68, 0x4f, 0x5b,
	0xd0, 0x93, 0x47, 0xf5, 0x0d, 0x8a, 0xf7, 0x65, 0x92, 0x8e, 0x25, 0x90, 0x64, 0x42, 0x76, 0x5a,
	0xd4, 0x27, 0xf5, 0x71, 0xa4, 0xc9, 0xee, 0xc5, 0xdb, 0xfc, 0xdf, 0xff, 0xc3, 0xf0, 0x01, 0x58,
	0x76, 0xb1, 0x4b, 0x99, 0x85, 0xd5, 0xe5, 0xe9, 0xee, 0xe9, 0x4b, 0x28, 0xee, 0x28, 0x2f, 0xef,
	0xf6, 0xcc, 0x7b, 0x4f, 0x9b, 0x52, 0x9a, 0xc3, 0xe7, 0x46, 0x5c, 0xa0, 0x41, 0x30, 0xa4, 0xba,
	0xbf, 0xff, 0x6d, 0x60, 0xf6, 0xce, 0x2e, 0xaa, 0x5b, 0x68, 0x87, 0xef, 0x60, 0xd8, 0xeb, 0x66,
	0xd5, 0xac, 0x17, 0xdb, 0x31, 0xa9, 0x1b, 0x98, 0xa7, 0xec, 0x2c, 0xe9, 0xb3, 0x82, 0x6b, 0x50,
	0x0f, 0x70, 0x65, 0x31, 0x39, 0x41, 0xef, 0x7e, 0x50, 0x1c, 0x47, 0x7d, 0x5e, 0xea, 0x7f, 0x54,
	0x3d, 0xc2, 0x75, 0xa6, 0x81, 0xf2, 0x91, 0x7a, 0x83, 0x1e, 0xa3, 0x25, 0x3d, 0xab, 0xc3, 0x11,
	0xbf, 0x55, 0x7a, 0x7a, 0x7f, 0x64, 0x7f, 0x08, 0xa4, 0xe7, 0xf5, 0x7d, 0x4d, 0xea, 0x05, 0xc0,
	0x66, 0x42, 0xa1, 0x5d, 0x8f, 0xa2, 0xdb, 0x55, 0xb3, 0xbe, 0x78, 0x5a, 0x76, 0xd5, 0xaa, 0x9b,
	0xac, 0xba, 0x8f, 0xc9, 0x6a, 0xbb, 0x18, 0xd7, 0xaf, 0x62, 0xda, 0x52, 0x3f, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0x7e, 0xb0, 0xc2, 0x1f, 0x01, 0x00, 0x00,
}
